# Generated by Django 4.1.1 on 2023-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='identifier',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
