# Generated by Django 4.0.10 on 2023-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_video_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('is_expired', models.BooleanField(default=False)),
                ('domain', models.CharField(default='youtube.com', max_length=200)),
            ],
        ),
    ]
