version: '3'

services:
  django:
    build: .
    container_name: django
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/myapp
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A flagright.celery worker -l INFO
    volumes:
      - .:/myapp
    depends_on:
      - django
      - redis

  celerybeat:
    build: .
    command: celery -A flagright beat -l INFO
    restart: always
    depends_on:
      - django
      - celery
      - redis
      
  redis:
    image: "redis:alpine"
    container_name: redis
